-- MySQL Script generated by MySQL Workbench
-- Tue Mar 16 01:30:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema juvenil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema juvenil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `juvenil` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `juvenil` ;

-- -----------------------------------------------------
-- Table `juvenil`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juvenil`.`cargo` (
  `id_cargo` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `cargo` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `juvenil`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juvenil`.`cliente` (
  `id_cliente` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `razonsocial` VARCHAR(100) NULL DEFAULT NULL,
  `nit_cli` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `juvenil`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juvenil`.`empleado` (
  `id_empleado` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `id_cargo` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `ci` VARCHAR(20) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `paterno` VARCHAR(35) NULL DEFAULT NULL,
  `materno` VARCHAR(35) NULL DEFAULT NULL,
  `direccion` VARCHAR(60) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `fechanacimiento` DATE NULL DEFAULT NULL,
  `genero` CHAR(2) NULL DEFAULT NULL,
  `intereses` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`id_empleado`, `id_cargo`),
  INDEX `id_cargo` (`id_cargo` ASC) VISIBLE,
  CONSTRAINT `empleado_ibfk_1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `juvenil`.`cargo` (`id_cargo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `juvenil`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juvenil`.`compra` (
  `id_compra` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `id_empleado` INT UNSIGNED NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_compra`, `id_empleado`),
  INDEX `id_empleado` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `compra_ibfk_1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `juvenil`.`empleado` (`id_empleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `juvenil`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juvenil`.`proveedor` (
  `id_proveedor` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `empresa` VARCHAR(50) NULL DEFAULT NULL,
  `contacto` VARCHAR(50) NULL DEFAULT NULL,
  `mail` VARCHAR(50) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(60) NULL DEFAULT NULL,
  `logo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `juvenil`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juvenil`.`producto` (
  `id_producto` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `id_proveedor` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `nombreproducto` VARCHAR(70) NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `costocompra` FLOAT(12,2) NULL DEFAULT NULL,
  `costoventa` FLOAT(12,2) NULL DEFAULT NULL,
  `stock` INT UNSIGNED NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`, `id_proveedor`),
  INDEX `id_proveedor` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `juvenil`.`proveedor` (`id_proveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `juvenil`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juvenil`.`detalle_compra` (
  `id_compra` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `id_producto` INT UNSIGNED NOT NULL,
  `cantidadcompra` INT UNSIGNED NULL DEFAULT NULL,
  `costocompra` FLOAT(12,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_compra`, `id_producto`),
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `detalle_compra_ibfk_1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `juvenil`.`producto` (`id_producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `detalle_compra_ibfk_2`
    FOREIGN KEY (`id_compra`)
    REFERENCES `juvenil`.`compra` (`id_compra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `juvenil`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juvenil`.`venta` (
  `id_venta` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `id_empleado` INT UNSIGNED NOT NULL,
  `id_cliente` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `decha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_venta`, `id_empleado`, `id_cliente`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `id_empleado` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `venta_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `juvenil`.`cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `venta_ibfk_2`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `juvenil`.`empleado` (`id_empleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `juvenil`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juvenil`.`detalle_venta` (
  `id_venta` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `id_producto` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `cantidad` INT UNSIGNED NULL DEFAULT NULL,
  `costo` FLOAT(12,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_venta`, `id_producto`),
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `detalle_venta_ibfk_1`
    FOREIGN KEY (`id_venta`)
    REFERENCES `juvenil`.`venta` (`id_venta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `detalle_venta_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `juvenil`.`producto` (`id_producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `juvenil`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juvenil`.`usuarios` (
  `id_empleado` INT UNSIGNED AUTO_INCREMENT NOT NULL,
  `usuario` VARCHAR(35) NULL DEFAULT NULL,
  `password` VARCHAR(65) NULL DEFAULT NULL,
  `nivel` INT NULL DEFAULT NULL,
  `estado` VARCHAR(25) NULL DEFAULT NULL,
  `id_usuario` INT AUTO_INCREMENT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_empleado`),
  INDEX `id_empleado` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `juvenil`.`empleado` (`id_empleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
